# Generated by Django 4.2.6 on 2023-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0009_lead_date_added_lead_description_lead_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, unique=tuple),
        ),
    ]
