# Generated by Django 4.2.6 on 2023-11-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0010_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
