# Generated by Django 4.2.6 on 2023-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0011_alter_lead_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
