[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "djcrm.settings"
python_files = ["test_*.py", "*_test.py", "tests.py"]

[tool.pylint.MASTER]
load-plugins = "pylint_django"
django-settings-module = "djcrm.settings"
disable = ["missing-docstring", "too-many-ancestors"]
ignore = "manage.py"
ignore-paths = ".*/migrations/.*"
